### ISSUE TITLE
More verbose output

### ISSUE THREAD

**Issue by gtamas** [pmmp/extension-stub-generator#2]
Hi

So this works fine, but it only generates the classes, methods and method arguments.

Is it possible to generate more verbose output? For example:

- Description for each function and method with info about the arguments. I'm thinking of the kind of info you find in PHPDoc style comments etc.
- Info about method and function return types

Thanks in advance and great work!

**Comment by dktapps** [comment]
This tool depends entirely on the information in extension's arginfo. If the extension doesn't include parameter / return types, they won't appear in the generated code.

PHPDocs can't be generated because extensions don't provide PHPDoc.
